-->create a users table-->
CREATE TABLE USERS(
    USER_ID VARCHAR(20),
    USER_NAME VARCHAR(20),
    EMAIL VARCHAR(20),
    PRIMARY KEY(USER_ID)
);
INSERT INTO USERS
VALUES(2, 'TRUPTHI', 'betty546@gmail.com');
INSERT INTO USERS
VALUES(3, 'SHREYA', 'getty546@gmail.com');
INSERT INTO USERS
VALUES(4, 'SHREYA', 'getty546@gmail.com');
-->QUERY TO RETREIVE DUPLICATE VALUES
SELECT USER_ID,
    USER_NAME,
    EMAIL
FROM USER